# Generated by Django 4.0.4 on 2022-05-23 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_profile_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='household',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.household'),
        ),
    ]
