# Generated by Django 4.0.4 on 2022-05-24 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_profile_household'),
        ('app', '0004_alter_profile_household 2'),
    ]

    operations = [
    ]
