# Generated by Django 4.0.4 on 2022-05-24 15:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_merge_20220524_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='expiry',
            field=models.DateField(default=datetime.date(2022, 5, 31)),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
