# Generated by Django 4.0.4 on 2022-05-25 20:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_food_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='expiry',
            field=models.DateField(default=datetime.date(2022, 6, 1)),
        ),
    ]
