# Generated by Django 4.0.4 on 2022-05-25 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_food_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hosuehold_manager',
            field=models.BooleanField(default=False),
        ),
    ]
