# Generated by Django 4.0.4 on 2022-05-25 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_profile_hosuehold_manager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='hosuehold_manager',
            new_name='household_manager',
        ),
    ]
