# Generated by Django 4.0.4 on 2022-05-26 00:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_hosuehold_manager_profile_household_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='expiry',
            field=models.DateField(default=datetime.date(2022, 6, 2)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='household',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(None), to='app.household'),
        ),
    ]
